spring.servlet.multipart.max-file-size=3GB
spring.servlet.multipart.max-request-size=3GB
spring.servlet.multipart.file-size-threshold=0B
spring.servlet.multipart.location=${java.io.tmpdir}
server.tomcat.threads.max=100
server.tomcat.threads.min-spare=10
server.tomcat.accept-count=100
server.tomcat.max-swallow-size=-1
server.tomcat.max-http-form-post-size=-1
springdoc.swagger-ui.path=/swagger-ui.html
heat-network.portfolio.parallelism=8
