"""Generate an offline Fly Heatnet UI demo replay.

This script is intentionally independent from the main Java solver. It creates
an artificial `UI_DEMO` replay that exercises the viewer contract without
claiming to run a trained model or an engineering checker.
"""

from __future__ import annotations

import json
from pathlib import Path


ROOT = Path(__file__).resolve().parents[1]
OUT = ROOT / "examples" / "ui_demo.json"


def feature(fid, object_type, geometry, **props):
    payload = {"id": fid, "object_type": object_type}
    payload.update(props)
    return {
        "type": "Feature",
        "properties": payload,
        "geometry": geometry,
    }


def point(x, y):
    return {"type": "Point", "coordinates": [x, y]}


def line(*coords):
    return {"type": "LineString", "coordinates": [[x, y] for x, y in coords]}


def polygon(*coords):
    ring = [[x, y] for x, y in coords]
    if ring[0] != ring[-1]:
        ring.append(ring[0])
    return {"type": "Polygon", "coordinates": [ring]}


def fc(features):
    return {"type": "FeatureCollection", "features": features}


def segment(fid, coords, status="accepted", diameter=100, message=""):
    return feature(
        fid,
        "heat_network",
        line(*coords),
        network_role="new",
        status=status,
        diameter=diameter,
        message=message,
    )


def metrics(connected, length, cost, score, status="VALID", action_ms=18):
    return {
        "connected_oks": connected,
        "total_oks": 4,
        "flow_tph": 37.4 if connected == 4 else 28.2,
        "new_network_length_m": length,
        "cost_rub": cost,
        "score": score,
        "checker_status": status,
        "action_ms": action_ms,
        "animation_ms": 1050,
    }


def build():
    input_features = [
        feature("src-1", "heat_source", point(70, 370), label="Source"),
        feature("cam-1", "heat_chamber", point(190, 370), network_role="existing"),
        feature("old-1", "heat_network", line((70, 370), (190, 370), (330, 360)), network_role="existing", diameter=500),
        feature("oks-1", "oks_connection_point", point(520, 210), flow_tph=9.1),
        feature("oks-2", "oks_connection_point", point(720, 255), flow_tph=8.4),
        feature("oks-3", "oks_connection_point", point(620, 470), flow_tph=12.5),
        feature("oks-4", "oks_connection_point", point(840, 505), flow_tph=7.4),
        feature("bld-1", "restriction", polygon((470, 165), (560, 165), (560, 245), (470, 245)), restriction_type="oks"),
        feature("bld-2", "restriction", polygon((675, 210), (760, 210), (760, 295), (675, 295)), restriction_type="oks"),
        feature("bld-3", "restriction", polygon((575, 425), (665, 425), (665, 515), (575, 515)), restriction_type="oks"),
        feature("bld-4", "restriction", polygon((795, 462), (890, 462), (890, 548), (795, 548)), restriction_type="oks"),
        feature("park-1", "restriction", polygon((405, 300), (555, 300), (555, 395), (405, 395)), restriction_type="park"),
        feature("road-1", "restriction", polygon((320, 135), (365, 135), (365, 565), (320, 565)), restriction_type="road"),
        feature("water-1", "restriction", polygon((695, 355), (930, 355), (930, 410), (695, 410)), restriction_type="water"),
    ]

    initial_segments = [
        segment("new-0-a", ((190, 370), (360, 370), (515, 260)), diameter=125, message="B2-C initial branch"),
        segment("new-0-b", ((515, 260), (520, 210)), diameter=80, message="Final approach"),
    ]

    step1_after = initial_segments + [
        segment("new-1-a", ((515, 260), (700, 258), (720, 255)), diameter=100, message="Shared branch to oks-2"),
    ]

    rejected_candidate = [
        segment(
            "cand-2-a",
            ((515, 260), (620, 340), (620, 470)),
            status="rejected",
            diameter=125,
            message="Rejected: crosses park buffer",
        )
    ]

    step3_after = step1_after + [
        segment("new-3-a", ((360, 370), (505, 420), (620, 470)), diameter=125, message="Legal bypass"),
    ]

    step4_after = step3_after + [
        segment("new-4-a", ((620, 470), (730, 528), (840, 505)), diameter=100, message="Water-safe lower crossing"),
    ]

    return {
        "schema_version": "fly-replay-v1",
        "mode": "UI_DEMO",
        "coordinate_system": "LOCAL_METERS",
        "provenance": "Synthetic offline demo generated by experimental/fly-heatnet/scripts/generate_ui_demo.py",
        "input": fc(input_features),
        "initial": fc(initial_segments),
        "initial_metrics": metrics(1, 343.5, 49700000, 18.76, action_ms=0),
        "steps": [
            {
                "id": "step-001",
                "operation": "JUNCTION_TO_OKS",
                "message": "Connect oks-2 through the existing shared branch.",
                "status": "committed",
                "candidate": fc([step1_after[-1]]),
                "after": fc(step1_after),
                "metrics_after": metrics(2, 530.8, 68200000, 15.21, action_ms=21),
            },
            {
                "id": "step-002",
                "operation": "DIRECT_BRANCH",
                "message": "Reject a visually short branch because checker flags the park buffer.",
                "status": "rejected",
                "candidate": fc(rejected_candidate),
                "after": fc(step1_after),
                "metrics_after": metrics(2, 530.8, 68200000, 15.21, status="REJECTED", action_ms=14),
            },
            {
                "id": "step-003",
                "operation": "BYPASS_REPAIR",
                "message": "Route oks-3 around the restricted park area.",
                "status": "committed",
                "candidate": fc([step3_after[-1]]),
                "after": fc(step3_after),
                "metrics_after": metrics(3, 802.4, 94800000, 12.64, action_ms=29),
            },
            {
                "id": "step-004",
                "operation": "WATER_SAFE_EXTENSION",
                "message": "Add a lower branch to oks-4 without crossing the water polygon.",
                "status": "committed",
                "candidate": fc([step4_after[-1]]),
                "after": fc(step4_after),
                "metrics_after": metrics(4, 1032.7, 124900000, 9.88, action_ms=33),
            },
        ],
    }


def main():
    OUT.parent.mkdir(parents=True, exist_ok=True)
    OUT.write_text(json.dumps(build(), ensure_ascii=False, indent=2) + "\n", encoding="utf-8")
    print(f"wrote {OUT}")


if __name__ == "__main__":
    main()

